print("Hello World")
print("Nama Saya Prima Sakti")
print("Hobi Saya BErmain Bola")
print("Saya Berumur 15 Tahun")
print("Saya Tinggal Di Depok")
print("Sekolah Di Smk HArapan Bangsa")
print("Game Kesukaan Saya Growtopia")
print("Saya Lahir Di Bulan Februari")
print("Makanan Favorit Ayam")
print("Cita-Cita Saya Menjadi Pengusaha")